// libFuzzer harness for the Alpaca frame parser.
//
// The parser is the one component that touches untrusted input (bytes off a
// socket), so it must never crash, read out of bounds, or invoke UB on
// arbitrary data — it should only ever throw on malformed JSON. This harness
// feeds fuzzer-generated bytes straight into Parser::parse and lets the
// sanitizers (address/undefined) catch anything worse than an exception.
//
// Apple clang ships no libFuzzer runtime, so build with Homebrew LLVM:
//   "$(brew --prefix llvm)/bin/clang++" -std=c++20 -g -O1 \
//     -fsanitize=fuzzer,address,undefined \
//     -I src -I "$(brew --prefix simdjson)/include" \
//     tests/fuzz_parser.cpp src/ingest/parser.cpp \
//     "$(brew --prefix simdjson)/lib/libsimdjson.dylib" -o fuzz_parser
//   ./fuzz_parser -max_total_time=30

#include <cstddef>
#include <cstdint>
#include <exception>
#include <string_view>

#include "ingest/parser.h"

extern "C" int LLVMFuzzerTestOneInput(const std::uint8_t* data,
                                      std::size_t size) {
    static ohlcv::ingest::Parser parser;  // reused, as in production
    try {
        parser.parse(std::string_view{reinterpret_cast<const char*>(data), size});
    } catch (const std::exception&) {
        // Throwing on malformed input is the parser's documented contract —
        // expected, not a finding. Only a crash / sanitizer trip is a bug.
    }
    return 0;
}
